[package]
name = "csv2template"
version = "0.1.0"
authors = ["drklee3 <derrick@dlee.dev>"]
edition = "2018"

[dependencies]
chrono = "0.4.13"
clap = "2.33.2"
csv = "1.1.3"
env_logger = "0.7"
heck = "0.3"
log = "0.4"
tera = "1.4.0"
