[package]
name = "csv2template"
version = "0.1.0"
authors = ["drklee3 <derrick@dlee.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tera = "1.4.0"
csv = "1.1.3"
clap = "2.33.2"
chrono = "0.4.13"
heck = "0.3"
